protobuf_source_dir=/Users/blueberry/code/xhs/my/protobubf_blueberry
cp -f ${protobuf_source_dir}/src/google/protobuf/arena.h ./header/google/protobuf/arena.h
cp -f ${protobuf_source_dir}/src/google/protobuf/arenastring.h   ./header/google/protobuf/arenastring.h
cp -f ${protobuf_source_dir}/src/google/protobuf/extension_set.h ./header/google/protobuf/extension_set.h
cp -f ${protobuf_source_dir}/src/google/protobuf/generated_message_util.h ./header/google/protobuf/generated_message_util.h
cp -f ${protobuf_source_dir}/src/google/protobuf/implicit_weak_message.h ./header/google/protobuf/implicit_weak_message.h
cp -f ${protobuf_source_dir}/src/google/protobuf/parse_context.h ./header/google/protobuf/parse_context.h
cp -f ${protobuf_source_dir}/src/google/protobuf/io/coded_stream.h ./header/google/protobuf/io/coded_stream.h
cp -f ${protobuf_source_dir}/src/google/protobuf/io/strtod.h ./header/google/protobuf/io/strtod.h
cp -f ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream.h ./header/google/protobuf/io/zero_copy_stream.h
cp -f ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream_impl_lite.h ./header/google/protobuf/io/zero_copy_stream_impl_lite.h
cp -f ${protobuf_source_dir}/src/google/protobuf/message_lite.h ./header/google/protobuf/message_lite.h
cp -f ${protobuf_source_dir}/src/google/protobuf/repeated_field.h ./header/google/protobuf/repeated_field.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/bytestream.h ./header/google/protobuf/stubs/bytestream.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/common.h ./header/google/protobuf/stubs/common.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/int128.h ./header/google/protobuf/stubs/int128.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/once.h ./header/google/protobuf/stubs/once.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/status.h ./header/google/protobuf/stubs/status.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/statusor.h ./header/google/protobuf/stubs/statusor.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/stringpiece.h ./header/google/protobuf/stubs/stringpiece.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/stringprintf.h ./header/google/protobuf/stubs/stringprintf.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/strutil.h ./header/google/protobuf/stubs/strutil.h
cp -f ${protobuf_source_dir}/src/google/protobuf/stubs/time.h ./header/google/protobuf/stubs/time.h
cp -f ${protobuf_source_dir}/src/google/protobuf/wire_format_lite.h ./header/google/protobuf/wire_format_lite.h
